Repository gomyway1216/rag, pull requests merged in 2024-11, with the labels that each got.

#60 :construction_worker: Remove `huyfififi` from Dependabot reviewer
  .github/dependabot.yml
Labels: chore

#69 Update 2024_11.md more coding
  plan_and_progress/2024_11.md
Labels: self-enhancement

#74 now the plan and progress files should be deleted
  plan_and_progress/2024_11.md
Labels: self-enhancement

#76 Insert chunk, get response to questions.
  scripts/add_chunk.py
  scripts/ask_query.py
Labels: enhancement

#77 Chunk size comparison. combined add_chunk.py and ask_query.py
  scripts/add_chunk.py
  scripts/ask_query.py
  scripts/evaluate_chunk_size.py
  scripts/evaluate_chunk_size_results/response_1732849305_half_a_paragraph.txt
  scripts/evaluate_chunk_size_results/response_1732849305_paragraph.txt
  scripts/evaluate_chunk_size_results/response_1732849305_quarter_a_paragraph.txt
  scripts/evaluate_chunk_size_results/response_1732849305_sentence.txt
Labels: enhancement
