Repository gomyway1216/rag, pull requests merged in 2024-10, with the labels that each got.

#31 :construction_worker: Trigger GitHub Actions workflows on PR creation
  .github/workflows/lint-backend.yml
  .github/workflows/test-backend.yml
Labels: enhancement

#33 :arrow_up: Bump openai from 1.47.1 to 1.51.0
  poetry.lock
  pyproject.toml
Labels: dependencies

#34 :bug: Fix a warning filter
  pyproject.toml
Labels: chore

#35 rephrased response when no relevant information is found
  main.py
Labels: enhancement

#36 updated message body
  main.py
Labels: enhancement

#39 Add RAG explanation to README.md
  README.md
Labels: documentation

#38 Add a folder for articles that explain NLP basics
  nlp_basics_articles/01_Neural-Networks-Basics.md
  nlp_basics_articles/02_Natural-Language-Processing-Basics.md
Labels: documentation

#41 :recycle: Refactor directory structure
  Dockerfile
  app/__init__.py
  app/api/main.py
  app/api/routes/__init__.py
  app/api/routes/chat.py
  app/main.py
  app/models.py
  app/tests/__init__.py
  app/tests/api/__init__.py
  app/tests/api/routes/__init__.py
  app/tests/api/routes/test_chat.py
  app/tests/conftest.py
Labels: enhancement

#47 Carolina museum nlp article update
  nlp_basics_articles/02_Natural-Language-Processing-Basics.md
  nlp_basics_articles/03_Natural-Language-Processing-Models.md
Labels: documentation

#45 created API endpoint to calculate BMI
  app/api/main.py
  app/api/routes/health.py
  app/models.py
Labels: good first issue

#49 :white_check_mark: Add a test example for BMI API
  app/models.py
  app/tests/api/routes/test_health.py
Labels: tests

#56 Chunk size document
  data/RAG_chunk_evaluation_questions.txt
  data/chapterXX.txt
  documents/chunk_size.md
Labels: documentation
